### ISSUE TITLE
NetBSD/hpcmips (MobilePro 800, mipsel)

### ISSUE THREAD

**Issue by hackerb9** [classilla/cryanc#19]
Hi! Although NetBSD has perfectly fine crypto in its current incarnation, that would require me updating my NEC Mobile Pro 800 from NetBSD version 1.6 (circa 2002) to NetBSD 10 (circa now). I figured, I'd first try _Crypto Ancienne_ and see if it would work well enough to serve my purposes.

Despite the documentation still saying that NO_FUNNY_ALIGNMENT presumes big endian, it works fine on this mipsel machine, probably thanks to ba9696e536e230d8b75227e1b552263b935dd947. This is the only change needed:

```C
#if defined(__MIPSEL__)
#define NO_FUNNY_ALIGNMENT
#endif
```

If you want you can add `and defined (__NetBSD__)` in there, but I suspect any mipsel machine is going to care deeply about alignment.

_____

<sub>By the way, while this is a very neat project, it turns out it doesn't actually do what I need. Even the hoary version of w3m I have installed insists on using `CONNECT`, so _Crypto Ancienne_ won't work for me.</sub>

**Comment by hackerb9** [comment]
I know nothing about newer MIPS cores. I've heard the newer chips are quite different from the "classics", like the VR4121 in the MobilePro 800. 

Perhaps the impact on newer devices would be limited: I read on the linux-mips wiki that the vast majority of 64-bit MIPS machines are run big endian, and thus wouldn't be affected by my suggestion.

**Comment by classilla** [comment]
Decided to add a `FUNNY_ALIGNMENT_OK` and specific block, and if we find a flexible MIPS, we can add it as an exception.
