### ISSUE TITLE
POST Requests

### ISSUE THREAD

**Issue by rafaeldfdias** [classilla/cryanc#23]
Hi,
first of all congrats for the great lib!
quick question: I tried to use carl, from the command line and I was wondering if there is a specific syntax to define a post request header and body? Is there is, is that documented somewhere?  

Thanks

**Comment by classilla** [comment]
You do this in proxy mode with `-p`, but pass the request over standard input (i.e., you'll need to build your own HTTP request, starting with the `POST` command, followed by your payload). This applies for any other HTTP method that isn't `GET` or `HEAD`, like `PUT`.

**Comment by rafaeldfdias** [comment]
Thanks for the fast response. 
Ran the command like this: 
echo -e "POST /v1/request HTTP/1.1\r\nHost: api.myservice.com\r\nContent-Type: application/json\r\nAuthorization: Bearer XQV8asdhasdjhMEFROMT3BlbkFJ3DTYIzqUAhQJ7JF29YYO\r\n\r\n{\"key1\": \"value1\", \"key2\": \"value2\"}" | ./carl https://api.myservice.com -p

However, I get the response that my Authorization header was not defined. Am I here missing something?

**Comment by classilla** [comment]
The request should be made as a proxy would. Remove `https://api.myservice.com` from the `./carl` command and change your `POST` request to `POST https://api.myservice.com/v1/request` and it should work.

**Comment by rafaeldfdias** [comment]
That worked. Thanks for your help!
