### ISSUE TITLE
IE5 16bit cannot work with carl

### ISSUE THREAD

**Issue by roytam1** [classilla/cryanc#9]
I tried to tell IE5 to use carl but ending up getting error page.

EDIT: after some read in https://docs.mitmproxy.org/stable/concepts-howmitmproxyworks/#explicit-https , I found this will be troublesome to implement.

**Comment by classilla** [comment]
That's because IE5 only knows how to use CONNECT-based methods. You'd need to use Squid bumping or something similar, which is out of scope for carl.
